config/routes.rb
Shop::Application.routes.draw do
  get "categories/index"
  root 'categories#index'

  resources :categories
  resources :products

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  validates :name, :description, :price, :category_id, presence: true
  validates :name, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category].permit(:name))

    if @category.save
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(params[:category].permit(:name))
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @products = Product.all
    @products_cat = Product.select { |p|  p.category_id == @category.id }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def destroy
    @product = Product.find(params[:id])
    @category = @product.category_id
    @product.destroy

    redirect_to category_path(@category)
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(params[:product].permit(:name, :description, :price, :category_id))
      redirect_to @product
    else
      render 'edit'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def index
    @product = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(params[:product].permit(:name, :description, :price, :category_id))

    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
    <% if @category.errors.any? %>
        <div id="errorExplanation">
          <h2><%= pluralize(@category.errors.count, "error") %> prohibited
            this post from being saved:</h2>
          <ul>
            <% @category.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :nazwa %><br>
      <%= f.text_field :name %>
    </p>
      <%= f.submit "OK" %>
    </p>
<% end %>

app/views/categories/edit.html.erb
<h1>Zmiana nazwy kategorii</h1>

<%= render 'form' %>

<%= link_to 'Powrót', category_path %>

app/views/categories/index.html.erb
<h1>Prosty sklep</h1>

<p>
  Wybierz kategorię:
  <% @categories.each do |c| %>
      <b><%= link_to c.name, c %></b>
  <% end %>

</p>
<%= link_to "Nowa kategoria", new_category_path %><br>
<%= link_to "Nowy produkt", new_product_path %>

app/views/categories/new.html.erb
<h1>Nowa kategoria</h1>

<%= render 'form' %>

<%= link_to 'Powrót', categories_path %>

app/views/categories/show.html.erb
<h1>Prosty sklep</h1>

<p>
  Wybierz kategorię:
  <% @categories.each do |c| %>
      <% if c != @category %>
        <b><%= link_to c.name, c %></b>
      <% else %>
        <b><%= c.name %></b>
      <% end %>
  <% end %>
</p>
<%= link_to "Nowa kategoria", new_category_path %>
<%= link_to "Edytuj kategorię", edit_category_path(@category) %>
<%= link_to "Usuń kategorię", category_path(@category), method: :delete, data: { confirm: 'Na bank?' } %>

<hr size="3" color="black" />

<h3>Produkty</h3>

<table border="3">
  <tr>
    <th>Nazwa</th>
    <th>Cena</th>
  </tr>

  <% @products_cat.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
		<td>
			<%= link_to "Więcej", product_path(product) %>
			<%= link_to "Edytuj", edit_product_path(product) %>
			<%= link_to "Usuń", product_path(product), method: :delete, data: { confirm: 'Na bank?' } %>
		</td>
	  </tr>
  <% end %>
</table><br>

<%= link_to "Nowy produkt", new_product_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
    <% if @product.errors.any? %>
        <div id="errorExplanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited
            this post from being saved:</h2>
          <ul>
            <% @product.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :nazwa %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :opis %><br>
      <%= f.text_area :description %>
    </p>
    <p>
      <%= f.label :cena %><br>
      <%= f.text_field :price %>
    </p>
    <p>
      <%= f.label :kategoria %><br>
      <%= f.select :category_id, Category.all.map{|category| [category.name.to_s, category.id]} %><br>

    </p>
    <%= f.submit "OK" %>
    </p>
<% end %>

app/views/products/edit.html.erb
<h1>Edytuj produkt</h1>

<%= render 'form' %>

<%= link_to 'Powrót', category_path(@product.category_id) %>

app/views/products/new.html.erb
<h1>Nowy produkt</h1>

<%= render 'form' %>

<%= link_to 'Powrót', categories_path %>

app/views/products/show.html.erb
<p>
  <strong>Nazwa:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Opis:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Cena:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Kategoria:</strong>
  <%= Category.all.find(@product.category_id).name.to_s %>
</p>

<%= link_to 'Edytuj produkt', edit_product_path(@product) %> |
<%= link_to 'Powrót', category_path(@product.category_id) %>